---
title: "CASA0005 Coursework - Code"
output: html_document
editor_options: 
  chunk_output_type: console
---
### Packages
```{r}
library(tidyverse)
library(raster)
library(rgdal)
library(sf)
library(tmap)
library(leafpop)
library(leaflet)
library(htmltools)
library(GISTools)
library(RColorBrewer)
library(BAMMtools)
```

### Read in Concentration Rasters
```{r}
# List the full file paths of all the raster files.
PollutionFiles <- list.files("Data/Air Pollution/LAEI 2016 Concentrations", ".tif", full.names = TRUE)

# Stack the raster files into a single stack.
PollutionConc <- stack(PollutionFiles)

# List the raster names.
PollutionNames <- c("NO2", "PM2.5")

# Rename the raster files.
names(PollutionConc) <- PollutionNames

# Set BNG coordinate system.
BNG = "+init=epsg:27700"

# Set WGS84 coordinate system.
WGS84 = "+init=epsg:4326"

# Reproject raster stack into BNG.
PollutionConc <- projectRaster(PollutionConc, crs= WGS84)

```

### Crop Raster Data
```{r}
# Read in the London boundary.
OutlineLondon <- st_read("Data/Boundaries and Census/statistical-gis-boundaries-london/London_Boundary.shp")

# Transform CRS into WGS84.
OutlineLondon <- st_transform(OutlineLondon, WGS84)

# Set extent to the London area.
ExtentLondon <- extent(OutlineLondon)

# Crop the rasters to the London outline.
CropNO2 <- crop(PollutionConc[[1]], OutlineLondon)
CropPM2.5 <- crop(PollutionConc[[2]], OutlineLondon)

# Mask rasters to the London outline.
MaskNO2 <-  mask(PollutionConc[[1]], OutlineLondon, na.rm=TRUE)
MaskPM2.5 <-  mask(PollutionConc[[2]], OutlineLondon, na.rm=TRUE)

# Stack the masked rasters.
PollutionLondon <- stack(MaskNO2, MaskPM2.5)
```

### Read in Boundaries
```{r}
# Read in boundaries as spatial polygons.
LAD <- st_read("Data/Boundaries and Census/statistical-gis-boundaries-london/London_Borough_Excluding_MHW.shp")
MSOA <- st_read("Data/Boundaries and Census/statistical-gis-boundaries-london/MSOA_2011_London_gen_MHW.shp")
LSOA <- st_read("Data/Boundaries and Census/statistical-gis-boundaries-london/LSOA_2011_London_gen_MHW.shp")

# Convert from an sp object to sf object.
SFLAD <- st_as_sf(LAD)
SFMSOA <- st_as_sf(MSOA)
SFLSOA <- st_as_sf(LSOA)

# Transform CRS to WGS84.
SFLAD <- st_transform(SFLAD, WGS84)
SFMSOA <- st_transform(SFMSOA, WGS84)
SFLSOA <- st_transform(SFLSOA, WGS84)

# Select relevent columns.
SFLAD <- SFLAD[,c(1, 2, 8)]
SFMSOA <- SFMSOA[,c(2, 1, 4, 3, 13)]
SFLSOA <- SFLSOA[,c(2, 1, 4, 3, 6, 5, 15)]

# Rename columns.
colnames(SFLAD) <- c("LAD Name", "LAD Code", "geometry")
colnames(SFMSOA) <- c("MSOA Name", "MSOA Code", "LAD Name", "LAD Code", "geometry")
colnames(SFLSOA) <- c("LSOA Name", "LSOA Code", "MSOA Name", "MSOA Code","LAD Name", "LAD Code", "geometry")

```

### Read in School, GP and Hospital Data
```{r}
# Read in code points.
AllCodePoints <- read_csv("Data/Schools and Health/OS Point Codes/Data/AllCodePoints.csv",
                       locale = locale(encoding = "latin1"),
                       na = "n/a")

# Read in  data.
Schools <- read_csv("Data/Schools and Health/All School Locations 2016.csv",
                       locale = locale(encoding = "latin1"),
                       na = "n/a")
GPs <- read_csv("Data/Schools and Health/GP Locations.csv",
                       locale = locale(encoding = "latin1"),
                       na = "n/a")
Hospitals <- read_csv("Data/Schools and Health/Hospital Locations.csv",
                       locale = locale(encoding = "latin1"),
                       na = "n/a")
# Select the necessary columns.
Schools <- Schools[,c(3, 8)]
GPs <- GPs[,c(1, 9)]
Hospitals <- Hospitals[,c(1, 9)]

# Rename Columns.
colnames(Schools) <- c("Name", "Postcode")
colnames(GPs) <- c("Name", "Postcode")
colnames(Hospitals) <- c("Name", "Postcode")

# Classify data.
Schools$Type <- "School"
GPs$Type <- "GP"
Hospitals$Type <- "Hospital"

# Merge school, GP and hospital points.
Locations <- rbind(Schools, GPs, Hospitals)

# Remove space in postcodes
Locations$Postcode <- gsub(" ","", Locations$Postcode)

# Attach code points.
Locations<-merge(Locations, 
             AllCodePoints, 
             by.x="Postcode", 
             by.y="Postcode",
             no.dups = TRUE)

# Reorder columns
Locations <- Locations[,c(2, 1, 3, 4, 5)]

# Remove duplicates.
Locations <- Locations[!duplicated(Locations$Name), ]

```

### Extract Concentrations for Schools, GPs and Hospitals
```{r}
# Convert location coordinates into point geometry.
SFLocations <- st_as_sf(Locations, coords = c("Eastings", "Northings"), crs = BNG)

# Transform CRS into WGS84.
SFLocations <- st_transform(SFLocations, WGS84)

# Select points inside London.
SFLocations <- SFLocations[SFLAD,]

# Extract concentrations.
SFLocations$`NO2 (µg/m³)`<- raster::extract(PollutionConc[[1]], SFLocations)
SFLocations$`PM2.5 (µg/m³)`<- raster::extract(PollutionConc[[2]], SFLocations)

# Round concentrations to 2 d.p..
SFLocations$`NO2 (µg/m³)` <- round(SFLocations$`NO2 (µg/m³)`, digits = 2)
SFLocations$`PM2.5 (µg/m³)` <- round(SFLocations$`PM2.5 (µg/m³)`, digits = 2)

# Rename columns.
colnames(SFLocations) <- c("Building Name", "Postcode", "Building Type", "geometry", "NO2 (µg/m³)", "PM2.5 (µg/m³)")

# Extract schools, GPs and hospitals that exceed WHO guides
SFLocationsNO2 <- SFLocations %>% filter(`NO2 (µg/m³)` > 40)
SFLocationsPM2.5 <- SFLocations %>% filter(`PM2.5 (µg/m³)` > 10)

```

### Subset Location Data and Set Up Popups
```{r}
SFSchools <- subset(SFLocations, `Building Type` == "School")

SFGPs <- subset(SFLocations, `Building Type` == "GP")

SFHospitals <- subset(SFLocations, `Building Type` == "Hospital")

SFSchoolsNO2 <- subset(SFLocationsNO2, `Building Type` == "School")

SFGPsNO2 <- subset(SFLocationsNO2, `Building Type` == "GP")

SFHospitalsNO2 <- subset(SFLocationsNO2, `Building Type` == "Hospital")

SFSchoolsPM2.5 <- subset(SFLocationsPM2.5, `Building Type` == "School")

SFGPsPM2.5 <- subset(SFLocationsPM2.5, `Building Type` == "GP")

SFHospitalsPM2.5 <- subset(SFLocationsPM2.5, `Building Type` == "Hospital")

```

### Ward Data for Points
```{r}
# Convert SF objects into SP objects
SPMSOA <- as(SFMSOA, "Spatial")
SPSchools <- as(SFSchools, "Spatial")
SPGPs <- as(SFGPs, "Spatial")
SPHospitals <- as(SFHospitals, "Spatial")
SPSchoolsNO2 <- as(SFSchoolsNO2, "Spatial")
SPGPsNO2 <- as(SFGPsNO2, "Spatial")
SPHospitalsNO2 <- as(SFHospitalsNO2, "Spatial")
SPSchoolsPM2.5 <- as(SFSchoolsPM2.5, "Spatial")
SPGPsPM2.5 <- as(SFGPsPM2.5, "Spatial")
SPHospitalsPM2.5 <- as(SFHospitalsPM2.5, "Spatial")

# Transform CRS to BNG (a projected CRS).
SPMSOA <- spTransform(SPMSOA, BNG)
SPSchools <- spTransform(SPSchools, BNG)
SPGPs <- spTransform(SPGPs, BNG)
SPHospitals <- spTransform(SPHospitals, BNG)
SPSchoolsNO2 <- spTransform(SPSchoolsNO2, BNG)
SPGPsNO2 <- spTransform(SPGPsNO2, BNG)
SPHospitalsNO2 <- spTransform(SPHospitalsNO2, BNG)
SPSchoolsPM2.5 <- spTransform(SPSchoolsPM2.5, BNG)
SPGPsPM2.5 <- spTransform(SPGPsPM2.5, BNG)
SPHospitalsPM2.5 <- spTransform(SPHospitalsPM2.5, BNG)

# Count the number of points in each MSOA.
SPMSOA@data$SchoolCount <- poly.counts(SPSchools, SPMSOA)
SPMSOA@data$GPCount <- poly.counts(SPGPs, SPMSOA)
SPMSOA@data$HospitalCount <- poly.counts(SPHospitals, SPMSOA)
SPMSOA@data$SchoolNO2Count <- poly.counts(SPSchoolsNO2, SPMSOA)
SPMSOA@data$GPNO2Count <- poly.counts(SPGPsNO2, SPMSOA)
SPMSOA@data$HospitalNO2Count <- poly.counts(SPHospitalsNO2, SPMSOA)
SPMSOA@data$SchoolPM2.5Count <- poly.counts(SPSchoolsPM2.5, SPMSOA)
SPMSOA@data$GPPM2.5Count <- poly.counts(SPGPsPM2.5, SPMSOA)
SPMSOA@data$HospitalPM2.5Count <- poly.counts(SPHospitalsPM2.5, SPMSOA)

# Calculate point density.
SPMSOA@data$SchoolDensity <- round(SPMSOA@data$SchoolCount/(poly.areas(SPMSOA)/1000000), digits = 3)
SPMSOA@data$GPDensity <- round(SPMSOA@data$GPCount/(poly.areas(SPMSOA)/1000000), digits = 3)
SPMSOA@data$HospitalDensity <- round(SPMSOA@data$HospitalCount/(poly.areas(SPMSOA)/1000000), digits = 3)
SPMSOA@data$SchoolNO2Density <- round(SPMSOA@data$SchoolNO2Count/(poly.areas(SPMSOA)/1000000), digits = 3)
SPMSOA@data$GPNO2Density <- round(SPMSOA@data$GPNO2Count/(poly.areas(SPMSOA)/1000000), digits = 3)
SPMSOA@data$HospitalNO2Density <- round(SPMSOA@data$HospitalNO2Count/ (poly.areas(SPMSOA)/1000000), digits = 3)
SPMSOA@data$SchoolPM2.5Density <- round(SPMSOA@data$SchoolPM2.5Count/ (poly.areas(SPMSOA)/1000000), digits = 3)
SPMSOA@data$GPPM2.5Density <- round(SPMSOA@data$GPPM2.5Count/ (poly.areas(SPMSOA)/1000000), digits = 3)
SPMSOA@data$HospitalPM2.5Density <- round(SPMSOA@data$HospitalPM2.5Count / (poly.areas(SPMSOA)/1000000), digits = 3)

# Convert SP MSOA data into a data frame.
SFMSOA <- st_as_sf(SPMSOA)

# Transform CRS to WGS
SFMSOA <- st_transform(SFMSOA, WGS84)

# Rename columns.
colnames(SFMSOA) <- c("MSOA Name", "MSOA Code", "LAD Name", "LAD Code", "School (All) Count", "GP (All) Count", "Hospital (All) Count", "School (NO2) Count", "GP (NO2) Count", "Hospital (NO2) Count", "School (PM2.5) Count", "GP (PM2.5) Count", "Hospital (PM2.5) Count", "School (All) Density", "GP (All) Density", "Hospital (All) Density", "School (NO2) Density", "GP (NO2) Density", "Hospital (NO2) Density", "School (PM2.5) Density", "GP (PM2.5) Density", "Hospital (PM2.5) Density", "geometry")

```

### Popup Tables and Palettes For Point Data
```{r}
# Create copies of the point data.
PopLAD <- SFLAD
PopMSOA <- SFMSOA
PopLSOA <- SFLSOA
PopSchools <- SFSchools
PopGPs <- SFGPs
PopHospitals <- SFHospitals
PopSchoolsNO2 <- SFSchoolsNO2
PopGPsNO2 <- SFGPsNO2
PopHospitalsNO2 <- SFHospitalsNO2
PopSchoolsPM2.5 <- SFSchoolsPM2.5
PopGPsPM2.5 <- SFGPsPM2.5
PopHospitalsPM2.5 <- SFHospitalsPM2.5

# Remove geometry data.
st_geometry(PopLAD) <- NULL
st_geometry(PopMSOA) <- NULL
st_geometry(PopLSOA) <- NULL
st_geometry(PopSchools) <- NULL
st_geometry(PopGPs) <- NULL
st_geometry(PopHospitals) <- NULL
st_geometry(PopSchoolsNO2) <- NULL
st_geometry(PopGPsNO2) <- NULL
st_geometry(PopHospitalsNO2) <- NULL
st_geometry(PopSchoolsPM2.5) <- NULL
st_geometry(PopGPsPM2.5) <- NULL
st_geometry(PopHospitalsPM2.5) <- NULL

# Create popup tables.
PopLAD <- popupTable(PopLAD, feature.id = FALSE, row.numbers = FALSE, zcol=c("LAD Name", "LAD Code"))
PopMSOA <- popupTable(PopMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "MSOA Code", "LAD Name", "LAD Code"))
PopLSOA <- popupTable(PopLSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("LSOA Name", "LSOA Code", "MSOA Name", "MSOA Code", "LAD Name", "LAD Code"))
PopSchools <- popupTable(PopSchools, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))
PopGPs <- popupTable(PopGPs, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))
PopHospitals <- popupTable(PopHospitals, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))
PopSchoolsNO2 <- popupTable(PopSchoolsNO2, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))
PopGPsNO2 <- popupTable(PopGPsNO2, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))
PopHospitalsNO2 <- popupTable(PopHospitalsNO2, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))
PopSchoolsPM2.5 <- popupTable(PopSchoolsPM2.5, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))
PopGPsPM2.5 <- popupTable(PopGPsPM2.5, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))
PopHospitalsPM2.5 <- popupTable(PopHospitalsPM2.5, feature.id = FALSE, row.numbers = FALSE, zcol=c("Building Name", "Postcode", "Building Type", "NO2 (µg/m³)", "PM2.5 (µg/m³)"))

# Create colour palettes.
PalAll <- colorFactor(c("LightSkyBlue", "RoyalBlue", "LightGreen"), levels = c("GP", "Hospital", "School"))
PalWHO <- colorFactor(c("Orange", "Red", "Gold"), levels = c("GP", "Hospital", "School"))
PalNO2 <- colorBin("OrRd", domain = NULL, bins = c(0, (getJenksBreaks(SFLocations$`NO2 (µg/m³)`, k=6)+0.001), 320), na.color = "transparent")
PalPM2.5 <- colorBin("OrRd", domain = NULL, bins = c(0, (getJenksBreaks(SFLocations$`PM2.5 (µg/m³)`, k=6)+0.001), 90), na.color = "transparent")
```

### Popup Tables and Palettes For Ward Data
```{r}
# Create copies of the MSOA data.
PopDataMSOA <- SFMSOA

# Remove geometry data.
st_geometry(PopDataMSOA) <- NULL

# Create popup tables.
PopSchoolsMSOA <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "School (All) Count", "School (All) Density"))
PopGPsMSOA <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "GP (All) Count", "GP (All) Density"))
PopHospitalsMSOA <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "Hospital (All) Count", "Hospital (All) Density"))
PopSchoolsMSOANO2 <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "School (NO2) Count", "School (NO2) Density"))
PopGPsMSOANO2 <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "GP (NO2) Count", "GP (NO2) Density"))
PopHospitalsMSOANO2 <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "Hospital (NO2) Count", "Hospital (NO2) Density"))
PopSchoolsMSOAPM2.5 <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "School (PM2.5) Count", "School (PM2.5) Density"))
PopGPsMSOAPM2.5 <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "GP (PM2.5) Count", "GP (PM2.5) Density"))
PopHospitalsMSOAPM2.5 <- popupTable(PopDataMSOA, feature.id = FALSE, row.numbers = FALSE, zcol=c("MSOA Name", "Hospital (PM2.5) Count", "Hospital (PM2.5) Density"))

# Create palettes.
PalSchoolsMSOA <- colorBin("GnBu", domain = PopDataMSOA$`School (All) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`School (All) Density`, k=5)+0.001)))
PalGPsMSOA <- colorBin("GnBu", domain = PopDataMSOA$`GP (All) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`GP (All) Density`, k=5)+0.001)))
PalHospitalsMSOA <- colorBin("GnBu", domain = PopDataMSOA$`Hospital (All) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`Hospital (All) Density`, k=5)+0.001)))
PalSchoolsMSOANO2 <- colorBin("OrRd", domain = PopDataMSOA$`School (NO2) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`School (NO2) Density`, k=5)+0.001)))
PalGPsMSOANO2 <- colorBin("OrRd", domain = PopDataMSOA$`GP (NO2) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`GP (NO2) Density`, k=5)+0.001)))
PalHospitalsMSOANO2 <- colorBin("OrRd", domain = PopDataMSOA$`Hospital (NO2) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`Hospital (NO2) Density`, k=5)+0.001)))
PalSchoolsMSOAPM2.5 <- colorBin("OrRd", domain = PopDataMSOA$`School (PM2.5) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`School (PM2.5) Density`, k=5)+0.001)))
PalGPsMSOAPM2.5 <- colorBin("OrRd", domain = PopDataMSOA$`GP (PM2.5) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`GP (PM2.5) Density`, k=5)+0.001)))
PalHospitalsMSOAPM2.5 <- colorBin("OrRd", domain = PopDataMSOA$`Hospital (PM2.5) Density`, bins = c(0, (getJenksBreaks(PopDataMSOA$`Hospital (PM2.5) Density`, k=5)+0.001)))
```

### Plot Point Map using leaflet
```{r}
# Map using leaflet.
MapLeaflet <- leaflet() %>% 
  addTiles(group = "OSM (default)") %>% 
  setView(-0.10, 51.5, zoom = 10) %>% 
  addRasterImage(PollutionLondon[[1]], colors = PalNO2, opacity = 1.0, group = "NO2 Concentration") %>%
  addRasterImage(PollutionLondon[[2]], colors = PalPM2.5, opacity = 1.0, group = "PM2.5 Concentration") %>%

  addPolygons(data = SFLAD, 
              fill = "transparent", 
              color = "black",
              stroke = "black",
              weight = 2, 
              opacity = 1.0, 
              fillOpacity = 0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 3,bringToFront = FALSE),
              popup = PopLAD,
              group = "LAD"
              ) %>% 
  addPolygons(data = SFMSOA, 
              fill = "transparent",
              color = "black",
              stroke = "black", 
              weight = 1.0, 
              opacity = 1.0, 
              fillOpacity = 0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = FALSE),
              popup = PopMSOA,
              group = "MSOA"
              ) %>% 
  addPolygons(data = SFLSOA, 
              fill = "transparent",
              color = "black",
              stroke = "black", 
              weight = 0.5, 
              opacity = 1.0, 
              fillOpacity = 0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 2, bringToFront = FALSE),
              popup = PopLSOA,
              group = "LSOA"
              ) %>% 
  
  addPolygons(data = SFMSOA, 
              fillColor = ~PalSchoolsMSOA(`School (All) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopSchoolsMSOA,
              group = "MSOA Schools (All)"
              ) %>% 
  addPolygons(data = SFMSOA, 
              fillColor = ~PalGPsMSOA(`GP (All) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopGPsMSOA,
              group = "MSOA GPs (All)"
              ) %>% 
  addPolygons(data = SFMSOA, 
              fillColor = ~PalHospitalsMSOA(`Hospital (All) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopHospitalsMSOA,
              group = "MSOA Hospitals (All)"
              ) %>% 
  
  addPolygons(data = SFMSOA, 
              fillColor = ~PalSchoolsMSOANO2(`School (NO2) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopSchoolsMSOANO2,
              group = "MSOA Schools (NO2)"
              ) %>% 
  addPolygons(data = SFMSOA, 
              fillColor = ~PalGPsMSOANO2(`GP (NO2) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopGPsMSOANO2,
              group = "MSOA GPs (NO2)"
              ) %>% 
  addPolygons(data = SFMSOA, 
              fillColor = ~PalHospitalsMSOANO2(`Hospital (NO2) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopHospitalsMSOANO2,
              group = "MSOA Hospitals (NO2)"
              ) %>% 

  addPolygons(data = SFMSOA, 
              fillColor = ~PalSchoolsMSOAPM2.5(`School (PM2.5) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopSchoolsMSOAPM2.5,
              group = "MSOA Schools (PM2.5)"
              ) %>% 
  addPolygons(data = SFMSOA, 
              fillColor = ~PalGPsMSOAPM2.5(`GP (PM2.5) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopGPsMSOAPM2.5,
              group = "MSOA GPs (PM2.5)"
              ) %>% 
  addPolygons(data = SFMSOA, 
              fillColor = ~PalHospitalsMSOAPM2.5(`Hospital (PM2.5) Density`),
              color = "black",
              stroke = "black", 
              weight = 0.1, 
              opacity = 1.0, 
              fillOpacity = 1.0,
              smoothFactor = 0.5,
              highlightOptions = highlightOptions(color = "white", weight = 1, bringToFront = TRUE),
              popup = PopHospitalsMSOAPM2.5,
              group = "MSOA Hospitals (PM2.5)"
              ) %>% 
  
  addCircleMarkers(data = SFSchools,
             radius = 5,
             fillColor = ~PalAll(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopSchools,
             group = "Schools (All)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'LightGreen'
                } else if (childCount < 100) {  
                  c = 'LightGreen'  
                } else { 
                  c = 'LightGreen'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className: 'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  addCircleMarkers(data = SFGPs,
             radius = 5,
             fillColor = ~PalAll(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopGPs,
             group = "GP (All)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'LightSkyBlue'
                } else if (childCount < 100) {  
                  c = 'LightSkyBlue'  
                } else { 
                  c = 'LightSkyBlue'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className: 'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  addCircleMarkers(data = SFHospitals,
             radius = 5,
             fillColor = ~PalAll(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopHospitals,
             group = "Hospital (All)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'RoyalBlue'
                } else if (childCount < 100) {  
                  c = 'RoyalBlue'  
                } else { 
                  c = 'RoyalBlue'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className: 'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  
  addCircleMarkers(data = SFSchoolsNO2,
             radius = 5,
             fillColor = ~PalWHO(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopSchoolsNO2,
             group = "Schools (NO2)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'Gold'
                } else if (childCount < 100) {  
                  c = 'Gold'  
                } else { 
                  c = 'Gold'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className: 'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  addCircleMarkers(data = SFGPsNO2,
             radius = 5,
             fillColor = ~PalWHO(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopGPsNO2,
             group = "GP (NO2)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'Orange'
                } else if (childCount < 100) {  
                  c = 'Orange'  
                } else { 
                  c = 'Orange'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className: 'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  addCircleMarkers(data = SFHospitalsNO2,
             radius = 5,
             fillColor = ~PalWHO(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopHospitalsNO2,
             group = "Hospital (NO2)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'Red'
                } else if (childCount < 100) {  
                  c = 'Red'  
                } else { 
                  c = 'Red'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className: 'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  
  addCircleMarkers(data = SFSchoolsPM2.5,
             radius = 5,
             fillColor = ~PalWHO(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopSchoolsPM2.5,
             group = "Schools (PM2.5)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'Gold'
                } else if (childCount < 100) {  
                  c = 'Gold'  
                } else { 
                  c = 'Gold'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className: 'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  addCircleMarkers(data = SFGPsPM2.5,
             radius = 5,
             fillColor = ~PalWHO(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopGPsPM2.5,
             group = "GP (PM2.5)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'Orange'
                } else if (childCount < 100) {  
                  c = 'Orange'  
                } else { 
                  c = 'Orange'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className: 'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  addCircleMarkers(data = SFHospitalsPM2.5,
             radius = 5,
             fillColor = ~PalWHO(`Building Type`),
             fillOpacity = 1.0,
             stroke = TRUE,
             color = "black",
             opacity = 1.0,
             weight = 1.0,
             popup = PopHospitalsPM2.5,
             group = "Hospital (PM2.5)",
             clusterOptions = markerClusterOptions(disableClusteringAtZoom = 13, iconCreateFunction=JS("function (cluster) {    
                var childCount = cluster.getChildCount();  
                if (childCount < 10) {  
                  c = 'Red'
                } else if (childCount < 100) {  
                  c = 'Red'  
                } else { 
                  c = 'Red'  
                }    
                return new L.DivIcon({ html: '<div style=\"background-color:'+c+'\"><span>' + childCount + '</span></div>', 
                className:  'marker-cluster', 
                iconSize: new L.Point(40, 40) });
              }"))
             ) %>% 
  
  addLayersControl(
    baseGroups = c("OSM (default)"),
    overlayGroups = c("NO2 Concentration", "PM2.5 Concentration", "LAD", "MSOA", "LSOA", "Schools (All)", "GP (All)", "Hospital (All)", "Schools (NO2)", "GP (NO2)", "Hospital (NO2)", "Schools (PM2.5)", "GP (PM2.5)", "Hospital (PM2.5)", "MSOA Schools (All)", "MSOA GPs (All)", "MSOA Hospitals (All)", "MSOA Schools (NO2)", "MSOA GPs (NO2)", "MSOA Hospitals (NO2)", "MSOA Schools (PM2.5)", "MSOA GPs (PM2.5)", "MSOA Hospitals (PM2.5)"),
    position = "topright",
    options = layersControlOptions(collapsed = TRUE)
    ) %>% 
  
  addLegend(pal = PalNO2, values = values(PollutionLondon[[1]]), title = "NO2 Concentration (µg/m³)", group = "NO2 Concentration") %>%
  addLegend(pal = PalPM2.5, values = values(PollutionLondon[[2]]), title = "PM2.5 Concentration (µg/m³)", group = "PM2.5 Concentration") %>%
  addLegend(pal = PalAll, values = SFLocations$`Building Type`, title = "All Buildings") %>% 
  addLegend(pal = PalWHO, values = SFLocationsNO2$`Building Type`, title = "Exceeding Limits") %>% 
  addLegend(pal = PalSchoolsMSOA, values = SFMSOA$`School (All) Density`, title = "School Density (per km2)", group = "MSOA Schools (All)") %>%
  addLegend(pal = PalGPsMSOA, values = SFMSOA$`GP (All) Density`, title = "GP Density (per km2)", group = "MSOA GPs (All)") %>%
  addLegend(pal = PalHospitalsMSOA, values = SFMSOA$`Hospital (All) Density`, title = "Hospital Density (per km2)", group = "MSOA Hospitals (All)") %>%
  addLegend(pal = PalSchoolsMSOANO2, values = SFMSOA$`School (NO2) Density`, title = "School NO2 Density (per km2)", group = "MSOA Schools (NO2)") %>%
  addLegend(pal = PalGPsMSOANO2, values = SFMSOA$`GP (NO2) Density`, title = "GP NO2 Density (per km2)", group = "MSOA GPs (NO2)") %>%
  addLegend(pal = PalHospitalsMSOANO2, values = SFMSOA$`Hospital (NO2) Density`, title = "Hospital NO2 Density (per km2)", group = "MSOA Hospitals (NO2)") %>%
  addLegend(pal = PalSchoolsMSOAPM2.5, values = SFMSOA$`School (PM2.5) Density`, title = "School PM2.5 Density (per km2)", group = "MSOA Schools (PM2.5)") %>%
  addLegend(pal = PalGPsMSOAPM2.5, values = SFMSOA$`GP (PM2.5) Density`, title = "GP PM2.5 Density (per km2)", group = "MSOA GPs (PM2.5)") %>%
  addLegend(pal = PalHospitalsMSOAPM2.5, values = SFMSOA$`Hospital (PM2.5) Density`, title = "Hospital PM2.5 Density (per km2)", group = "MSOA Hospitals (PM2.5)") %>%
  
  hideGroup(c("NO2 Concentration","PM2.5 Concentration", "Schools (NO2)", "GP (NO2)", "Hospital (NO2)", "Schools (PM2.5)", "GP (PM2.5)", "Hospital (PM2.5)", "MSOA Schools (All)", "MSOA GPs (All)", "MSOA Hospitals (All)", "MSOA Schools (NO2)", "MSOA GPs (NO2)", "MSOA Hospitals (NO2)", "MSOA Schools (PM2.5)", "MSOA GPs (PM2.5)", "MSOA Hospitals (PM2.5)")) %>% 
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to London",
    onClick=JS("function(btn, map){ map.setView([51.5, -0.10],10); }"))) %>% 
  addScaleBar(position = "bottomleft", 
              options = scaleBarOptions(metric = TRUE))
  
MapLeaflet
```

### Logistic Regression
```{r}
# Read in indices of deprivation data.
IDData <- read_csv("Data/Boundaries and Census/ID 2019 for London.csv",
                       locale = locale(encoding = "latin1"),
                       na = "n/a")
```

